name: CI

on:
  push:
  pull_request:

jobs:
  gradle-ci:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project sources
      uses: actions/checkout@v3
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - name: Format with ktlint
      run: ./gradlew ktlintFormat
    - name: Run build with Gradle Wrapper
      run: ./gradlew clean build